[package]
name = "basic-synth"
version = "0.1.0"
authors = ["George Kaplan <gkaplan@fearless.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midi-msg = "0.3.0"
midir = "0.7.0"
rodio = "0.14.0"
